<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login-Android-seconhand</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b852985c-6e69-471c-a168-753d2e0a4c30</testSuiteGuid>
   <testCaseLink>
      <guid>0aa8803c-8030-4f89-be52-2156ee8b9385</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login-Android/LoginPositiveAndroid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a2c8580-6b01-4442-8baa-31b6db8b1e46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99232b7b-5db2-4325-ad9d-c2662f0b677d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>91240309-07b7-4ac9-8246-772d89e73b37</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login-Android/LoginNegativeandroid1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c785c49-535b-42bb-8025-be2539f8cb23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f4eed26-7d05-4d89-bfce-d3e4dcb3e976</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a3e9705e-afc2-4a64-be9b-65c3f0b95865</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login-Android/LoginNegativeAndroid2</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5718afc6-6e71-4638-8a7f-60efc0dbc857</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0586b4d-1dcf-4b15-9c8d-1f6195edd88a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b027a277-af2e-4439-b519-6de7c792a04e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login-Android/LoginNegativeAndroid3</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdaf1081-1bd3-403b-abf0-877d71fabbfa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5bc54c77-08e0-453b-a1bc-b961610c2602</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
