<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login-Test-Suite-with-Data-Binding</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>11ec2ff5-bea5-463c-9ad4-483a69d9259e</testSuiteGuid>
   <testCaseLink>
      <guid>3f7b3419-aae8-485c-8fff-8dd656691100</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>e00d05c0-8a88-4eaf-b06b-34bf35e2d1c8</id>
         <masked>false</masked>
         <name>flag</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/homepage/login-using-data-binding</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f04f81b1-aac9-42e7-a3d5-687100caac5a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/data file login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f04f81b1-aac9-42e7-a3d5-687100caac5a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>description</value>
         <variableId>4e113027-0c7e-4bcb-be3b-e1f692b80946</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f04f81b1-aac9-42e7-a3d5-687100caac5a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>1ebc1ec2-7525-4097-b924-585988d369e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f04f81b1-aac9-42e7-a3d5-687100caac5a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>e8f30978-190b-4ec6-b524-3804d2303e40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f04f81b1-aac9-42e7-a3d5-687100caac5a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>flag</value>
         <variableId>e00d05c0-8a88-4eaf-b06b-34bf35e2d1c8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
