<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>WebSeconhand</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>da1b4670-4570-4c36-9979-c946cf566f09</testSuiteGuid>
   <testCaseLink>
      <guid>d9ec2c5d-8896-4d91-b986-59f942a126ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WebLogin/Loginpositive/Web-Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcd365cd-6f1a-4827-b007-961f1572428b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ab20cf9-781b-46da-afd1-d829a96eb135</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>da81a16f-cb94-4d5f-afba-399e54ae7903</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WebLogin/Loginndatabinding/Web-Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>55500344-e913-48f8-95ec-43fe7c53176f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/SecondLogin</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>55500344-e913-48f8-95ec-43fe7c53176f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>description</value>
         <variableId>fb1766ff-fac8-4e66-979e-e72920218970</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>55500344-e913-48f8-95ec-43fe7c53176f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>42e36551-b831-4a36-8a23-b3dd6c910016</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>55500344-e913-48f8-95ec-43fe7c53176f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>35c9f84a-0e2a-49de-b73d-d470098aec45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>55500344-e913-48f8-95ec-43fe7c53176f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>flag</value>
         <variableId>73993982-b9d0-454c-8f36-1f2b868cf34a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cecd8695-0559-4010-b303-817a914f320e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC-POSITIF/TC-0001 Register positif</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d69f9ff4-82cc-46b5-9f00-ea36928f1501</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4588cca-0713-4d0f-9d6e-dc06e3de5ec0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd432e4b-ebd4-4a89-94e3-288c7c1c6a53</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8fc91839-ed37-461e-bed1-a220d422b77e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC-NEGATIVE/TC-0001 Register negatif</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f70eb656-c829-4d20-b38d-e4009039ae0e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3498a9b8-924a-477e-932f-be960aac7409</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>090bd059-e2da-420f-8679-4ce0fcbc1a7e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>02e05558-f939-4303-8eb8-e57568965088</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WEB/SecondHandJual/TC001 - JualPositive</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a83295e4-5efa-428f-a6da-1ecd5d1ef5b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>335e54fc-9984-4870-8c2c-db234f655a15</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/homepage/login-using-data-binding</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c5ce8962-100e-4f9e-ac28-47a90220e283</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/data file login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>c5ce8962-100e-4f9e-ac28-47a90220e283</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>description</value>
         <variableId>4e113027-0c7e-4bcb-be3b-e1f692b80946</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c5ce8962-100e-4f9e-ac28-47a90220e283</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>1ebc1ec2-7525-4097-b924-585988d369e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c5ce8962-100e-4f9e-ac28-47a90220e283</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>e8f30978-190b-4ec6-b524-3804d2303e40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c5ce8962-100e-4f9e-ac28-47a90220e283</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>flag</value>
         <variableId>e00d05c0-8a88-4eaf-b06b-34bf35e2d1c8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b1c72085-ce40-4ec9-8f2e-b7489e02023e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/homepage/jual</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>bea738e0-3ca8-4720-b2e8-13b428be53b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/homepage/logout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>851fb8e6-5e58-46bd-a749-3f5f51455d31</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/detailkatalogpage/detail-katalog-saya-tertarik</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>feaa41fa-9c1f-434b-a56e-5135be209d06</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/detailkatalogpage/detail-katalog-swipe-left</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>7056195e-68b6-4caf-8fbc-a75b7861827f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/detailkatalogpage/detail-katalog-swipe-right</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0ce0c5a0-156a-4877-a9c4-e21f1a2ba938</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/detailkatalogpage/detail-katalog-validasi-deskripsi</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76762c62-fd8f-4393-b160-3efb9a44ed2d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6a756615-d145-489e-aaa4-6cb7d8a5ddd1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/detailkatalogpage/detail-katalog-validasi-gambar</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>94e571ec-cfdc-4a20-ba91-16bdcb41e566</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/beranda/beranda_Secondhand Store/TCBB001_validasiUIIconHome</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>bd768cbf-415e-4d50-b3c6-a130ea617e45</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/beranda/beranda_Secondhand Store/TCBB002_validasiUIGambarPadaKatalog</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e88be0db-ee65-4cdf-8928-11a00fec4114</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/beranda/beranda_Secondhand Store/TCBB003_validasiJudulDanKategoriProduk</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b46815b1-471c-48f7-ace9-680398b302af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/beranda/beranda_Secondhand Store/TCBB004_validasiMataUangDanNominal</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
